# settings.yaml
box_name: "generic/ubuntu2304"
vm:
- name: "controlplane"
  ip: "192.168.56.100"
  memory: "2048"
  cpus: "2"
- name: "node01"
  ip: "192.168.56.101"
  memory: "2048"
  cpus: "1"
- name: "node02"
  ip: "192.168.56.102"
  memory: "2048"
  cpus: "1"
