# settings.yaml
# box_name: "sloopstash/ubuntu-22-04"
box_name: "bento/ubuntu-22.04"
# box_version: "2.1.1"
vm:
- name: "controlplane"
  ip: "192.168.56.100"
  memory: "2048"
  cpus: "2"
- name: "node01"
  ip: "192.168.56.101"
  memory: "2048"
  cpus: "2"
- name: "node02"
  ip: "192.168.56.102"
  memory: "2048"
  cpus: "2"
- name: "node03"
  ip: "192.168.56.103"
  memory: "2048"
  cpus: "1"

